# Generated by Django 4.2.7 on 2024-02-01 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='snippest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('code', models.TextField()),
                ('linenos', models.BooleanField(default=False)),
                ('language', models.CharField(choices=[('pyton', 'pyhton'), ('java', 'java'), ('javascript', 'javascript'), ('c', 'c'), ('c++', 'c++'), ('c#', 'c#'), ('asp.net', 'asp.net')], max_length=50)),
                ('style', models.CharField(choices=[('friendly', 'friendly'), ('defaut', 'default')], max_length=30)),
            ],
        ),
    ]
