'''print("hello \'python'")
print('hello\"python"')
print("hello \npython")
print("hello \b python!")
print("hello\b python")
print(R"\t hello python !") 
'''
print("hello\'python'")
print('hello\"i am fine"')
print("hello\npython")
print("hello \b python!")
print("hello\b python!")
print("\t hello python ")
print(R"\t hello python!")